"""
Automated Security Regression Suite Generator.
Menghasilkan test script Pytest + httpx otomatis untuk setiap kerentanan
agar dapat diintegrasikan ke CI/CD pipeline untuk mencegah regresi bug keamanan.
"""

from typing import List, Dict, Any

class RegressionSuiteService:
    @staticmethod
    def generate_pytest_suite(target_url: str, vulnerabilities: List[Dict[str, Any]]) -> str:
        test_cases = []
        for index, vuln in enumerate(vulnerabilities, 1):
            title = vuln.get("title", f"Vulnerability {index}")
            endpoint = vuln.get("affected_endpoint", "/")
            cwe = vuln.get("cwe_id", "CWE-000")
            
            # Format endpoint
            path = endpoint.split(" ")[-1] if " " in endpoint else endpoint
            if not path.startswith("/") and not path.startswith("http"):
                path = "/" + path

            test_func = f"""
def test_regression_vuln_{index}_{cwe.lower().replace('-', '_')}():
    \"\"\"
    Security Regression Test: {title}
    Target Endpoint: {path}
    CWE: {cwe}
    Ensure payload is non-executable and returns clean protection response.
    \"\"\"
    url = f"{{BASE_URL}}{path}"
    
    # Test Payload
    test_payload = {{"q": "' OR 1=1 --", "input": "<script>alert('test')</script>"}}
    
    response = httpx.get(url, params=test_payload, timeout=10.0)
    
    # Assertion 1: Should not return 500 Internal Server Error (Unhandled Crash)
    assert response.status_code != 500, "Server crashed with 500 Internal Error during security payload probe"
    
    # Assertion 2: SQLi / XSS string should not be reflected unescaped
    if response.status_code == 200:
        assert "<script>alert('test')</script>" not in response.text, "XSS Payload reflected raw in response body!"
        assert "Syntax error in SQL" not in response.text, "Raw database SQL error message exposed!"
"""
            test_cases.append(test_func)

        suite_code = f"""# Automated Security Regression Test Suite
# Generated by SiteCure Platform
# Target: {target_url}

import pytest
import httpx

BASE_URL = "{target_url.rstrip('/')}"

{"".join(test_cases)}
if __name__ == "__main__":
    pytest.main(["-v", __file__])
"""
        return suite_code
